[linux_servers]
ansible_host=10.0.1.10
ansible_host=10.0.1.11

[linux_servers:vars]
ansible_user=ansible_svc_account
ansible_ssh_private_key_file=~/.ssh/id_rsa

# Routes all SSH connections through the jump host transparently
# ansible_ssh_common_args="-o ProxyJump=admin@jump.bank.local"


# Set Python interpreter if legacy systems are in use
ansible_python_interpreter=/usr/bin/python3

# Run ansible -i inventory.ini all -m ping to confirm your Ubuntu control node can successfully authenticate and connect to all target servers.